name: App Deployment

on:
  push:
    branches: [main]
    paths:
    - app/**

  pull_request:
    branches: [main]
    paths:
    - app/**

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Java 11
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11

      - name: Package
        run: |
          cd app
          mvn clean package

      - name: Upload to Azure Functions
        uses: Azure/functions-action@v1
        id: wheeler-resume-app
        with:
          app-name: wheeler-resume-app
          package: app/target/azure-functions/wheeler-resume-app
          publish-profile: ${{ secrets.AZURE_APP_AUTH }}

