name: App Deployment

on:
  push:
    branches: [main]
    paths:
      - 'app/**'

  pull_request:
    branches: [main]
    paths:
      - 'app/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Java 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Package
        run: |
          cd app
          mvn clean package

      - name: Upload Artifact
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: target
          path: app/target

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Java 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: target
          path: app/target

      - name: Upload to Azure Functions
        run: |
          mvn install package azure-functions:deploy
