name: Web Deployment

on:
  push:
    branches: [main]
    paths:
    - 'web/**'

  pull_request:
    branches: [main]
    paths:
      - 'web/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install Dependencies
        run: |
          cd web
          npm install
          npm install -g @angular/cli

      - name: Angular Build
        run: |
          cd web
          ng build --prod

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_WEB_AUTH }}

      - name: Upload to Blob
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
            az storage blob upload-batch --account-name wheelerresumeweb -d '$web' -s web/dist/web/

      - name: Purge CDN
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
            az cdn endpoint purge \
              --content-paths  "/*" \
              --name "wheelerresumeweb-cdn" \
              --profile-name "wheeler-resume-cdn" \
              --resource-group "CloudGuruChallenge_21.04"

      - name: Azure Logout
        run: |
          az logout
